# Generated by Django 5.2.13 on 2026-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_form_name_alter_student_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="college_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
