# Generated by Django 4.2.30 on 2026-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
